# Generated by Django 5.1 on 2024-09-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='guide_groups',
            fields=[
                ('groupCode', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=60)),
                ('guide_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guide')),
            ],
        ),
    ]
