# Generated by Django 5.1 on 2024-10-01 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_delete_guide_guide_groups_guide_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='guide_groups',
            name='guide_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
