# Generated by Django 5.1 on 2024-10-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guide_alter_guide_groups_guide_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.AlterModelOptions(
            name='guide_groups',
            options={'verbose_name_plural': 'Guide_group'},
        ),
    ]
