# Generated by Django 5.1 on 2024-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerstudent',
            name='id',
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
