# Generated by Django 5.1 on 2024-09-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0002_remove_registerstudent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='groupCode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
