# Generated by Django 5.1 on 2024-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0003_registerstudent_groupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='branch',
            field=models.CharField(default='COMPS', max_length=10),
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='groupNumber',
            field=models.CharField(default='00', max_length=5),
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='year',
            field=models.CharField(default='SY', max_length=5),
        ),
    ]
