# Generated by Django 5.1 on 2024-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0004_registerstudent_branch_registerstudent_groupnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='branch',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='year',
            field=models.CharField(default='00', max_length=5),
        ),
    ]
