# Generated by Django 5.1 on 2024-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0005_alter_registerstudent_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='projectName',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
