# Generated by Django 5.1 on 2024-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0006_registerstudent_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='projYear',
            field=models.CharField(default='00', max_length=15),
        ),
    ]
