# Generated by Django 5.1 on 2024-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0007_registerstudent_projyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='projYear',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
