# Generated by Django 5.1 on 2024-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_page', '0009_remove_registerstudent_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='groupCode',
            field=models.CharField(max_length=20),
        ),
    ]
